export class listaDevoluciones{
    row:any;
    numero:any;
    tipoPago:any;
    cantidad:any;
    claveRastreo:any;
    conceptoPago:any;
    institucionEmisora:any;
    cuentaOrdenante:any;
    tipoCuentaOrdenante:any;
    institucionReceptora:any;
    cuentaBeneficiaria:any;
    tipoCuentaBeneficiaria:any;
    fecha:any;
    instancia:any;
    seleccion!:boolean;
    pagoDev:string;
    paquete:number;
}